# Generated by Django 6.0.2 on 2026-02-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_friendrequest_userfriendcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='can_edit_recipes',
            field=models.BooleanField(default=False),
        ),
    ]
