# Generated by Django 6.0.2 on 2026-02-07 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_friendrequest_userfriendcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='can_edit_recipes_status',
            field=models.CharField(
                choices=[('none', 'none'), ('pending', 'pending'), ('accepted', 'accepted')],
                default='none',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='can_edit_recipes_requested_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='edit_recipes_requests_sent',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
