# Generated by Django 6.0.2 on 2026-02-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_menuslot_replace_user_with_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
