# Generated by Django 6.0.2 on 2026-03-09 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0007_add_is_primary_to_menu"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="menuslot",
            name="unique_menu_day_meal",
        ),
    ]
