# Generated by Django 6.0.2 on 2026-03-24 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0011_add_menuslot_servings_menushare_useractiveMenu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="is_primary",
        ),
    ]
